### ISSUE TITLE
Scroll is hidden in Heat Map

### ISSUE THREAD

**Issue by Diyarmo** [microsoft/responsible-ai-toolbox#1072] opened 2021-12-08 12:15 UTC
Hi there,

When I use the heat map only the first 13 rows of the "Feature 1" are shown and the rest of the rows are hidden.
![image](https://user-images.githubusercontent.com/43572673/145205628-49c91d1f-9249-4fa6-a741-4695edb1bcac.png)

in the above image 7 rows are hidden and normally there is no way I can see them.

I tried some changes in the CSS of the webpage and noticed that the overflow attribute of cohortsLayerHost2 div is set to "hidden".
![image](https://user-images.githubusercontent.com/43572673/145206296-4b27db00-9821-4c52-858a-42a234493a2d.png)

So, I changed the overflow to "auto" and the problem was fixed.

I did some search in the repository but I couldn't find the right file to change. can you please fix this bug?

**Comment by imatiach-msft** [comment] 2021-12-08 15:27
Great point. Maybe we can add a horizontal and vertical scroll bar.  I've heard this issue mentioned before by internal users actually, but I think there was some hesitancy in adding scroll bars to the UX and discussion around solving this through some sort of aggregation.  But the issue is probable most easily solved by adding the scroll bars.

**Comment by imatiach-msft** [comment] 2021-12-09 05:07
closing as fixed with merged pr #1074

**Closed by imatiach-msft** 2021-12-09 05:07 UTC
