### ISSUE TITLE
[ErrorAnalysis]: Switching to heatmap after creating a cohort from the tree shows the wrong error rate

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-toolbox#386] opened 2021-03-12 01:14 UTC
Steps to reproduce:

1- Create cohort from the tree
2- Don't click anywhere else, just go directly to the heatmap. It will not show the error rate of the current cohort, but of the one that was just created.

![image](https://user-images.githubusercontent.com/4303632/110876760-04f38580-828d-11eb-9fdb-91263823cb4f.png)

**Comment by imatiach-msft** [comment] 2022-01-06 13:38
@nushib this issue was from quite a while ago and I recall something similar to this being fixed, so closing this issue.  I'm not able to reproduce it locally.

**Closed by imatiach-msft** 2022-01-06 13:38 UTC
Labels: bug, Error Analysis
