### ISSUE TITLE
cannot create cohort in the "erroranalysis-dashboard-multiclass" example

### ISSUE THREAD

**Issue by jinyang08** [microsoft/responsible-ai-toolbox#961] opened 2021-10-19 03:39 UTC
Hi there,
 I tried to run the sample notebook "erroranalysis-dashboard-multiclass" on my local computer. For the section "Load simple ErrorAnalysis view without explanations" at around the 7th cell, the error analysis interface showed up normally, but the cohort is always "all data", which contains 89 testing samples. I tried to select two features in the heatmap tab but nothing happened. The cohort is all data and only the overall error rate was shown, no broken-down heatmap. A similar situation happened for the census example. Have I done something wrong here?
  Any help is appreciated.

![image](https://user-images.githubusercontent.com/71104563/137839910-bb719243-2fca-4ea2-863f-606ca4671e44.png)

**Comment by imatiach-msft** [comment] 2022-01-05 23:33
Oh, this dashboard doesn't work on databricks, this is a duplicate of:
https://github.com/microsoft/responsible-ai-toolbox/issues/944
That would explain the behavior you are seeing.
However, for local case it should work fine, but I can't reproduce the issue.
If you are still having problems in local case maybe we can have a call, otherwise I will close this issue.  Please feel free to reopen if you need help to debug more.

**Closed by imatiach-msft** 2022-01-05 23:33 UTC
