### ISSUE TITLE
[ErrorAnalysis] [Explanation]: The dependence plot needs a class picker so that it doesn't always focus on the same class

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-toolbox#388] opened 2021-03-12 01:27 UTC
![image](https://user-images.githubusercontent.com/4303632/110877803-dbd3f480-828e-11eb-85c7-c64fc07f447a.png)

**Comment by imatiach-msft** [comment] 2022-05-31 16:30
this issue is a duplicate of https://github.com/microsoft/responsible-ai-toolbox/issues/374 which is fixed with the PR https://github.com/microsoft/responsible-ai-toolbox/pull/1444

**Closed by imatiach-msft** 2022-05-31 16:30 UTC
Labels: Error Analysis, Explanation
